# Generated by Django 4.1 on 2023-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learneruser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="learneruser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="learneruser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="learneruser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="learneruser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="learneruser",
            name="username",
        ),
        migrations.AlterField(
            model_name="learneruser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="learneruser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="learneruser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
