# Generated by Django 4.1 on 2023-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_learneruser_options_alter_learneruser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learneruser",
            name="username",
            field=models.CharField(
                default="<django.db.models.fields.EmailField>", max_length=50
            ),
        ),
    ]
