# Generated by Django 4.1 on 2023-04-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_learneruser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learneruser",
            name="username",
            field=models.CharField(
                default=models.EmailField(max_length=254, unique=True), max_length=50
            ),
        ),
    ]
