# Generated by Django 4.1 on 2023-04-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_learneruser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="learneruser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
