# Generated by Django 4.1 on 2023-05-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_learneruser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learneruser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/static/images/avatar_none.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
