# Generated by Django 4.1 on 2023-05-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_learneruser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="learneruser",
            name="address",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="learneruser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learneruser",
            name="fullname",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="learneruser",
            name="gender",
            field=models.CharField(
                choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Giới tính khác")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="learneruser",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
