# Generated by Django 4.1 on 2023-04-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_flashcardtest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FlashCardtest",
        ),
    ]
