# Generated by Django 4.1 on 2023-05-21 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study", "0005_delete_flashcardtest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_flashcard",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
